### ISSUE TITLE
z-buffer styling of geodata removes culling

### ISSUE THREAD

**Issue by jrjdavidson** [melowntech/vts-browser-js#201]
Once z-buffer value is added, geodata become visible through objects - incuding through the globe ! I'm trying to figure out if this is an intended 'feature' or a bug?

I guess a workaround would be to add a fixed height when processing heights instead of using z-buffer, is it possible to do this in vts-browser or do i need to set a z height above ground in the original data?

Cheers

**Comment by davidmtech** [comment]
Setting z-buffer value is tricky. I do recommend to start with small values. i.e. 

        depthOffset : [-0.01,0,0]

more details depthOffset paramater can be found in [documentation](https://github.com/Melown/vts-browser-js/wiki/VTS-Browser-Renderer-API#definition-of-depthoffset). 

But unfortunately there is no optimal setting which works in all cases (some setting works for small zooms, another setting works big zooms). Another downside of current solution is that it applies correction per object not per pixel. Per pixel solution will have some performance penalty and will need support of WebGL extension (EXT_frag_depth) or WebGL 2. Unfortunately at this moment I am not able to tell when we will have free resources for development of this feature. 

Adding some extra height can help in some cases. There are two possible ways. In case you know height, you add some extra height and use 'fix' height mode. In case you do not know height, you use you extra height value as height (instead of zero) and use 'float' height mode. In 'float' height mode is height value interpreted as height above terrain.

**Comment by jrjdavidson** [comment]
Starting with small values solved it! thanks
